### ISSUE TITLE
[conflict] test-it plugin conflicting with SeleniumBase by cli args

### ISSUE THREAD

**Issue by dc-avasilev** [testit-tms/autotest-integration-python#10]
## systeminfo:
macos big sur 11.4
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
proc: 1,4 GHz 4‑core Intel Core i5
ram: 8 ГБ 2133 MHz LPDDR3
video: Intel Iris Plus Graphics 645 1536 МБ

shell:
zsh

plugin version:
testit-pytest==0.2.4

## Description
i have issue when clean install "testit-pytest", on my UI tests uses https://github.com/seleniumbase/SeleniumBase

```
Traceback (most recent call last):
  File "/Users/user1/webui_auto/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1175, in _preparse
    self.known_args_namespace = self._parser.parse_known_args(
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 146, in parse_known_args
    return self.parse_known_and_unknown_args(args, namespace=namespace)[0]
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 155, in parse_known_and_unknown_args
    optparser = self._getparser()
  File "/Users/user1/webui_auto/lib/python3.9/site-packages/_pytest/config/argparsing.py", line 122, in _getparser
    arggroup.add_argument(*n, **a)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1434, in add_argument
    return self._add_action(action)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1636, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1448, in _add_action
    self._check_conflict(action)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1585, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1594, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --start_page/--start-page/--url: conflicting option string: --url
```

## Steps to reproduce
requirements.txt
```
allure-pytest==2.9.43
allure-python-commons==2.9.43
deepdiff==5.5.0
pytest==6.2.4
python-magic==0.4.24
requests==2.25.1
seleniumbase==1.63.10
testit-pytest==0.2.4
```
try to run tests

## Actual behavior
i have a error `argparse.ArgumentError: argument --start_page/--start-page/--url: conflicting option string: --url`

## Expected behavior
tests runs correctly

## Notes
if i change local cli args in your code:
[.venv/lib/python3.9/site-packages/testit_pytest/plugin.py:20](https://github.com/testit-tms/autotest-integration-python/blob/main/testit_pytest/src/plugin.py#L20)
```
-- '--url',
++ '--testit_url',
```
it's help

**Comment by dc-avasilev** [comment]
https://github.com/testit-tms/autotest-integration-python/pull/11

**Comment by dc-avasilev** [comment]
fixed
